# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [5]:
#code here
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshapedarray = array.reshape(3, 4)

print("Original 1D array:,array\n",array)
print("\nReshaped 2D array:\n",reshapedarray)


array1 = np.array([[1, 2, 3]])
array2 = np.array([[4 ,5 , 6]])

concatenated_horizontal = np.concatenate((array1, array2), axis=1)
concatenated_vertical = np.concatenate((array1, array2), axis=0)

print("\nConcatenated Horizontally:\n",concatenated_horizontal)
print("\nConcatenated Vertically:\n",concatenated_vertical)



Original 1D array:,array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Concatenated Horizontally:
 [[1 2 3 4 5 6]]

Concatenated Vertically:
 [[1 2 3]
 [4 5 6]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [11]:
#code here
def classify_emails(emails):
    important_keywords = ['urgent', 'important', 'action required']
    promotions_keywords = ['deal', 'discount', 'promotion']
    spam_keywords = ['win', 'lottery', 'free', 'click now']

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        lowercase_email = email.lower()

        if any(keyword in lowercase_email for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in lowercase_email for keyword in promotions_keywords):
            promotions_emails.append(email)
        elif any(keyword in lowercase_email for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails


emails_to_classify = [
    "Urgent: Please review your account.",
    "Special Deal Inside - Limited Time Offer!",
    "Congratulations! You've won a prize.",
    "Meeting tomorrow at 3 PM.",
    "Get a 20% discount on your next purchase.",
    "Important: Action Required for Your Account.",
    "CongrCongratulations! you just win 50 tola gold. Click Now."
]

important, promotions, spam = classify_emails(emails_to_classify)

print("Important Emails:\n",important)
print("\nPromotions Emails:\n",promotions)
print("\nSpam Emails:\n",spam)




Important Emails:
 ['Urgent: Please review your account.', 'Important: Action Required for Your Account.']

Promotions Emails:
 ['Special Deal Inside - Limited Time Offer!', 'Get a 20% discount on your next purchase.']

Spam Emails:
 ['CongrCongratulations! you just win 50 tola gold. Click Now.']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [12]:
#code here

english_spanish_dict = {
    'hello': 'hola',
    'world': 'mundo',
    'cat': 'gato',
    'dog': 'perro',
    'thank you': 'gracias',
    'goodbye': 'adiós',
    'friend': 'amigo',
    'house': 'casa',
    'computer': 'computadora',
    'book': 'libro'
}

def translation():
    while True:
        user_input = input("Enter an English word (type 'exit' to quit): ").lower()

        if user_input == 'exit':
            print("Exiting the dictionary. Goodbye!")
            break

        if user_input in english_spanish_dict:
            print(f"The Spanish translation of '{user_input}' is: {english_spanish_dict[user_input]}")
        else:
            print(f"Translation not available for '{user_input}'. Please try another word.")


translation()


Enter an English word (type 'exit' to quit): hello
The Spanish translation of 'hello' is: hola
Enter an English word (type 'exit' to quit): wordl
Translation not available for 'wordl'. Please try another word.
Enter an English word (type 'exit' to quit): exit
Exiting the dictionary. Goodbye!


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [32]:
import pandas as pd

url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url)

print (df.head(1))
# Calculate the total global sales for all games in rhe dataset.
total_global_sales = df['Global_Sales'].sum()
print(f"\nTotal global sales for all games: {total_global_sales} million")

# Find the game with the highest global sales
max_global_sales_game = df.loc[df['Global_Sales'].argmax()]
print(f"\nGame with the highest global sales:\n{max_global_sales_game}")

# Determine the average sales for each region
average_sales_by_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("\nAverage sales for each region:")
print(average_sales_by_region)

# Find the top 5 most popular game genres based on global sales
top_genres_global_sales = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("\nTop 5 most popular game genres based on global sales:")
print(top_genres_global_sales)

# Calculate the total sales for each genre in each region
total_sales_by_genre_region = df.groupby(['Genre'])[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print("\nTotal sales for each genre in each region:")
print(total_sales_by_genre_region)

# Find the most popular genre in North America (NA_Sales)
most_popular_genre_na_sales = df.groupby('Genre')['NA_Sales'].sum().idxmax()
print("\nMost popular genre in North America (NA_Sales):", most_popular_genre_na_sales)

# Display last 10 rows
print("\nLast 10 rows of the dataset:")
print(df.tail(10))

# Determine the top 3 gaming platforms with the highest global sales
top3_platforms_global_sales = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("\nTop 3 gaming platforms with the highest global sales:")
print(top3_platforms_global_sales)

# Calculate the market share (percentage of global sales) for each genre
df['Market_Share'] = (df['Global_Sales'] / total_global_sales) * 100
market_share_by_genre = df.groupby('Genre')['Market_Share'].mean()
print("\nMarket share for each genre:")
print(market_share_by_genre)

# Calculate the correlation coefficient between NA_Sales and EU_Sales
correlation_na_eu_sales = df['NA_Sales'].corr(df['EU_Sales'])
print("\nCorrelation coefficient between NA_Sales and EU_Sales:", correlation_na_eu_sales)


   Rank        Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
0     1  Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

   JP_Sales  Other_Sales  Global_Sales  
0      3.77         8.46         82.74  

Total global sales for all games: 8920.44 million

Game with the highest global sales:
Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object

Average sales for each region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

Top 5 most popular game genres based on global sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: fl

In [17]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
